DROP TABLE Flight;
DROP TABLE Passenger;
DROP TABLE Airport;
DROP TABLE Country;
DROP TABLE Continent;
DROP TABLE Pilot;
DROP TABLE Status;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME = 'TemporaryTable')
BEGIN
    DROP TABLE TemporaryTable;
END